### ISSUE TITLE
Provide build instruction

### ISSUE THREAD

**Issue by senpl** [huextrat/Taskist#1]
Provide instruction how to build this app. I already figure out how to run it, still It crash just when app is starting. I just want how to build it and run, could be minimal.
`
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.huawei.lcagent.client.LogCollectManager.getUserType()' on a null object reference
02-05 10:43:27.554 18695-24742/? I/SendBroadcastPermission: action:com.google.android.gms.gcm.ACTION_SCHEDULE, mPermissionType:0
..
02-05 10:43:27.799 5216-5244/? E/FileUtils: srcFile is not a file
02-05 10:43:27.799 5216-5244/? E/LogDatabase: Could not move to uploading path.
02-05 10:43:27.807 2487-2487/? E/HAL: load: id=gralloc != hmi->id=gralloc
02-05 10:43:27.815 5216-5243/? E/PackageLogInfoManager: checkPackageLogState, cr: android.app.ContextImpl$ApplicationContentResolver@87d1b47, packageNames: null
02-05 10:43:27.907 2487-2487/? E/hwcomposer: setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied
02-05 10:43:28.006 2487-2487/? E/HAL: load: id=gralloc != hmi->id=gralloc`

**Comment by mosn** [comment]
Is this repo being maintained?

**Comment by mosn** [comment]
remove Admob plugin, It is not used in the app but for some reason it was in the dependencies

**Comment by senpl** [comment]
> remove Admob plugin, It is not used in the app but for some reason it was in the dependencies
This fix crash on start in android ???

**Comment by huextrat** [comment]
Hi all,
Should be fixed now, the repo is up-to-date

Thanks
